subgraphs:
  nodejs:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  java:
    routing_url: http://localhost:4002/graphql
    schema:
      subgraph_url: http://localhost:4002/graphql
  php:
    routing_url: http://localhost:4003
    schema:
      subgraph_url: http://localhost:4003
  python:
    routing_url: http://0.0.0.0:4004/graphql
    schema:
      subgraph_url: http://0.0.0.0:4004/graphql
